### PR TITLE
Adds Blynk functionality

### PR DESCRIPTION
**Pull request by jschrempp**
This version adds Blynk code in several areas:
1. Temperature and Humidity virtual pins. These can be read by a Blynk app.
2. Alarm condition calls Blynk.notify so the Blynk app can alert the user.

Note: This version will purposely generate a compile error because the user needs to put their personal Blynk authorization code into the app.

### CODE REVIEW

**Comment by jschrempp** [comment]
Should also note that I separated the time interval for reading the DHT11 from the time interval for publishing to the Particle cloud. This allows for the smoothed value to adjust quickly (4 seconds) while the cloud is updated every minute. The Blynk app will poll for updates so that is asynchronous to the other two.

**Comment by BobGlicksman** [comment]
I looked through your code and I understand the changes that you made.  They are fine with me.  This current version both publishes temperature and humidity to the Particle Cloud as well as making this data available to Blynk.  As such, it requires a user to have a Blynk account, even if they wish to use the Particle.publish() feature with their own app (e.g. IFTTT or something based on webhooks).  I therefore think that we need to add in some #define and #ifdef statements that allow a user to configure their firmware to either support publication of this data (to the Cloud) or to read it via Blynk virtual pins (or both, I guess, if they really have a need).  Having separated the cloud publication time from the sample time, it seems that there is an intent to support a user who wants to use publication and not have a Blynk account.

Since you are more familiar with Blynk than I am, would you be willing to make these changes and test that the various feature combinations work?  At that point, I believe that our firmware is ready for release (but not the hardware or documentation yet).

**Comment by jschrempp** [comment]
Or course, great idea. I'll so some ifdef's around the blynk
      code.
    Also note that at this time a blynk alarm will be sent only once,
      until the reset button is pressed. That isn't really the best
      since it could leave the alarm unarmed without any indication. I'm
      thinking about ways to address this
    1. Send another blynk alarm after some period of time if water is
      still present. Perhaps two hours. This can get annoying if you
      don't want to handle the problem for some reason. However, the
      user could turn off their blynk app on their phone to stop the
      alerts, so it is not out of their control.
    2. Add an indicator to the blynk app on whether the blynk alarm
      is armed or not. And probably a blynk button widget to arm/disarm
      the alerts.
    Other thoughts?
    Jim
    
    
    
    
    On 3/26/17 10:20 AM, Bob Glicksman
      wrote:
    
    
      I looked through your code and I understand the changes that
        you made. They are fine with me. This current version both
        publishes temperature and humidity to the Particle Cloud as well
        as making this data available to Blynk. As such, it requires a
        user to have a Blynk account, even if they wish to use the
        Particle.publish() feature with their own app (e.g. IFTTT or
        something based on webhooks). I therefore think that we need to
        add in some #define and #ifdef statements that allow a user to
        configure their firmware to either support publication of this
        data (to the Cloud) or to read it via Blynk virtual pins (or
        both, I guess, if they really have a need). Having separated the
        cloud publication time from the sample time, it seems that there
        is an intent to support a user who wants to use publication and
        not have a Blynk account.
      Since you are more familiar with Blynk than I am, would you be
        willing to make these changes and test that the various feature
        combinations work? At that point, I believe that our firmware is
        ready for release (but not the hardware or documentation yet).
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BobGlicksman/WaterLeakSensor","title":"BobGlicksman/WaterLeakSensor","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BobGlicksman/WaterLeakSensor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BobGlicksman in #9: I looked through your code and I understand the changes that you made.  They are fine with me.  This current version both publishes temperature and humidity to the Particle Cloud as well as making this data available to Blynk.  As such, it requires a user to have a Blynk account, even if they wish to use the Particle.publish() feature with their own app (e.g. IFTTT or something based on webhooks).  I therefore think that we need to add in some #define and #ifdef statements that allow a user to configure their firmware to either support publication of this data (to the Cloud) or to read it via Blynk virtual pins (or both, I guess, if they really have a need).  Having separated the cloud publication time from the sample time, it seems that there is an intent to support a user who wants to use publication and not have a Blynk account.\r\n\r\nSince you are more familiar with Blynk than I am, would you be willing to make these changes and test that the various feature combinations work?  At that point, I believe that our firmware is ready for release (but not the hardware or documentation yet)."}],"action":{"name":"View Pull Request","url":"https://github.com/BobGlicksman/WaterLeakSensor/pull/9#issuecomment-289299929"}}}

**Comment by BobGlicksman** [comment]
I added the old, non-Blynk code to the HW-TEST branch and I merged this version into my development branch.  This way, I have a version that does not require Blynk integration to use for PCB board and cabling hardware development and testing.  I think that it is easier to test this way.  When Blynk becomes optional (configurable), I will probably delete this older code from the HW-TEST branch.  For right now, I have merged pull request #9 so that I have both versions available.

**Pull request merged**
